# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(
        regex="^Prompt/~create/$",
        view=views.PromptCreateView.as_view(),
        name='Prompt_create',
    ),
    url(
        regex="^Prompt/(?P<pk>\d+)/~delete/$",
        view=views.PromptDeleteView.as_view(),
        name='Prompt_delete',
    ),
    url(
        regex="^Prompt/(?P<pk>\d+)/$",
        view=views.PromptDetailView.as_view(),
        name='Prompt_detail',
    ),
    url(
        regex="^Prompt/(?P<pk>\d+)/~update/$",
        view=views.PromptUpdateView.as_view(),
        name='Prompt_update',
    ),
    url(
        regex="^Prompt/$",
        view=views.PromptListView.as_view(),
        name='Prompt_list',
    ),
	url(
        regex="^PromptVersion/~create/$",
        view=views.PromptVersionCreateView.as_view(),
        name='PromptVersion_create',
    ),
    url(
        regex="^PromptVersion/(?P<pk>\d+)/~delete/$",
        view=views.PromptVersionDeleteView.as_view(),
        name='PromptVersion_delete',
    ),
    url(
        regex="^PromptVersion/(?P<pk>\d+)/$",
        view=views.PromptVersionDetailView.as_view(),
        name='PromptVersion_detail',
    ),
    url(
        regex="^PromptVersion/(?P<pk>\d+)/~update/$",
        view=views.PromptVersionUpdateView.as_view(),
        name='PromptVersion_update',
    ),
    url(
        regex="^PromptVersion/$",
        view=views.PromptVersionListView.as_view(),
        name='PromptVersion_list',
    ),
	url(
        regex="^Response/~create/$",
        view=views.ResponseCreateView.as_view(),
        name='Response_create',
    ),
    url(
        regex="^Response/(?P<pk>\d+)/~delete/$",
        view=views.ResponseDeleteView.as_view(),
        name='Response_delete',
    ),
    url(
        regex="^Response/(?P<pk>\d+)/$",
        view=views.ResponseDetailView.as_view(),
        name='Response_detail',
    ),
    url(
        regex="^Response/(?P<pk>\d+)/~update/$",
        view=views.ResponseUpdateView.as_view(),
        name='Response_update',
    ),
    url(
        regex="^Response/$",
        view=views.ResponseListView.as_view(),
        name='Response_list',
    ),
	url(
        regex="^Tag/~create/$",
        view=views.TagCreateView.as_view(),
        name='Tag_create',
    ),
    url(
        regex="^Tag/(?P<pk>\d+)/~delete/$",
        view=views.TagDeleteView.as_view(),
        name='Tag_delete',
    ),
    url(
        regex="^Tag/(?P<pk>\d+)/$",
        view=views.TagDetailView.as_view(),
        name='Tag_detail',
    ),
    url(
        regex="^Tag/(?P<pk>\d+)/~update/$",
        view=views.TagUpdateView.as_view(),
        name='Tag_update',
    ),
    url(
        regex="^Tag/$",
        view=views.TagListView.as_view(),
        name='Tag_list',
    ),
	]
