# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_responses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='scale',
            new_name='scale_max',
        ),
        migrations.AddField(
            model_name='prompt',
            name='scale_min',
            field=models.PositiveIntegerField(default=0, verbose_name='minimum value of likert scale'),
        ),
    ]
