# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_responses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='text',
            field=models.TextField(default=b'{object}', verbose_name='text, format can contain {object}'),
        ),
    ]
