# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_responses', '0002_auto_20171113_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='scale_min',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='minimum value of likert scale'),
        ),
    ]
