# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_responses', '0003_auto_20171113_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='scale_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='maximum value of likert scale'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='scale_min',
            field=models.IntegerField(blank=True, default=1, verbose_name='minimum value of likert scale'),
        ),
    ]
