# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_responses', '0004_prompt_user_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='user_unique',
        ),
    ]
