# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_responses', '0005_auto_20171129_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='name',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
