# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_responses', '0006_prompt_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='short label'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='name',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='promptset',
            name='name',
            field=models.SlugField(unique=True),
        ),
    ]
